### ISSUE TITLE
Repair problem

### ISSUE THREAD

**Issue by ghost** [eaufavor/Modern-New-Tab-Page-NoAd#1]
Hello,

thanks for the extension, really :)

when I install it within developer mode, everything is okay but ıf I install it with crx file, it is installing but sayin that: "Repair". So, when I click the repair, nothing happens...

I want install it with crx file because otherwise, chrome warned me everytime.. ("It has been installed with developer mode, please deactive it.. etc.)

**Comment by eaufavor** [comment]
I repacked the crx file with the newest chrome and the problem seems fixed for me.
I updated the crx file I'm [hosting](http://eaufavor.info/Modern-New-Tab-Page-NoAd.crx) . Tell me if it works for you now. 

Thanks.

**Comment by ghost** [comment]
Yes, good work! :) But now, chrome is disabling the extension because of not from store. So, we should install it without crx.. 
1. Use a decompressor for uncompress the crx file
2. Open the developer mode and load it. 
3. Or use eaufavor's git archive.
