### ISSUE TITLE
Multiple issues 

### ISSUE THREAD

**Issue by Droyk** [eaufavor/Modern-New-Tab-Page-NoAd#2]
You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.

Icon zoom your extension can only provide us tile zoom but not icon zoom there are lot of i cons i want to use but can't use because they become too small or too jaggy for e.g. if i try 1920x1200 image it become too small but if i try 195x69 it will too jaggy .makes it more ugly i have tried many resolutions spent hours on it but still i cant good results  make them more smooth make them antialiased i have seen many startpage and you start page doesn't provide that functionality 

Font color is not working .i can only see white font color on both backgounds nomatter the background light or dark..... 

make scroll bar more responsive i have 60 tiles and when i scroll through mouse wheel it scrolls to slow.....

and plz add a one more functionality select multiple through ctrl and open them 

and really thanxx for keeping it alive i cant thankk u enough 

and if you need more help to find bugs tell me

**Comment by eaufavor** [comment]
Thanks for reporting the problems. 

I fixed the font color problem. I also added an option to speed up scrolling via "more options" by disabling smooth scroll.  Tell me if these work for you.

I'm working on the rest issues. For icon zooming, could you give me some icon files or screenshots so that I can have a taste of the problem? Thanks.

**Comment by Droyk** [comment]
I am really glad to hear that you are working to fix the problems thanxxx
1. this is the image http://i.imgur.com/4jSHEap.png
   if i load this to your startpage it will become too small and too ugly for me to see it ....
   i have another start page but on that start page it will antialiased  the whole image no matter if it is small or big 
   i don't have any problem with icons on my another startpage because no matter what are the resolution i give to startpage it will automatically become smooth and zoomed enough for me too seee
2. http://i.imgur.com/ahHYkmz.png
3. for this see on the edges  https://www.youtube.com/yt/brand/media/image/YouTube-icon-full_color.png
4. see this this image is just too small and too edgy plz antialise it  this http://logok.org/wp-content/uploads/2014/08/YouTube-logo-play-icon.png

so i think that would be enough for you 

and 

some feature request 

1.. can you add separators i have 98 tiles this feature would make it easy for me to see them ...if you want an example for this i will give you that

**Comment by eaufavor** [comment]
@Droyk I made several changes to improve the quality of the logos.
1. logos now have more pixels so they look better 
2. logos are now larger
3. the extension now will remove transparent edges of a logo to fit the tiles better.

So, to me, the images you provided now look much better.
However, you need to re-add these images to each tab for the updates to take effect.

**Comment by Droyk** [comment]
[**@eaufavor**](https://github.com/eaufavor) commented on [Jan 30, 2016, 3:20 AM GMT+5:30](https://github.com/eaufavor/Modern-New-Tab-Page-NoAd/issues/2#issuecomment-176984963 "2016-01-29T21:50:55Z - Replied by Github Comment Enhancer"):
> [@Droyk](https://github.com/Droyk) I made several changes to improve the quality of the logos.
> 
> 1.  logos now have more pixels so they look better
> 2.  logos are now larger
> 3.  the extension now will remove transparent edges of a logo to fit the tiles better.
> 
> So, to me, the images you provided now look much better.  
> 
> However, you need to re-add these images to each tab for the updates to take effect.

ohh plz do you know just how much time i have spend on adding those icons .it will take forever .cant we just add multiple images .plz it will take too much time

**Comment by Droyk** [comment]
[**@eaufavor**](https://github.com/eaufavor) commented on [Jan 30, 2016, 3:20 AM GMT+5:30](https://github.com/eaufavor/Modern-New-Tab-Page-NoAd/issues/2#issuecomment-176984963):

> [@Droyk](https://github.com/Droyk) I made several changes to improve the quality of the logos.
> 1.  logos now have more pixels so they look better
> 2.  logos are now larger
> 3.  the extension now will remove transparent edges of a logo to fit the tiles better.
> 
> So, to me, the images you provided now look much better.  
> 
> However, you need to re-add these images to each tab for the updates to take effect.

**Really like the logos now lot improved.**

**1. but still the scroll bar isn't improve that much .it only does fast scrolling when smooth scrolling is not checked but when smooth scrolling is checked it will not go fast .....**

**2. and i have still some images/logos that look small .why can't you give the user full control over zoom 
the user will decide which type of zoom user wants for e.g. see this image** http://i.imgur.com/2CbdKMf.png

**3. Can you plz give the user the ability to select multiple tiles and open them  at once for e.g. if we press ctrl+click on tile then click again on a tile then click again on x no. of tiles and then the user will open context menu op open them at once. it is similar to windows explorer** 

<ins>_*_thanxx for adding the features @eaufavor *__</ins>:smiley: :smile:

**Comment by Droyk** [comment]
[**@eaufavor**](https://github.com/eaufavor) commented on [Jan 30, 2016, 3:20 AM GMT+5:30](https://github.com/eaufavor/Modern-New-Tab-Page-NoAd/issues/2#issuecomment-176984963 "2016-01-29T21:50:55Z - Replied by Github Comment Enhancer"):
> [@Droyk](https://github.com/Droyk) I made several changes to improve the quality of the logos.
> 
> 1.  logos now have more pixels so they look better
> 2.  logos are now larger
> 3.  the extension now will remove transparent edges of a logo to fit the tiles better.
> 
> So, to me, the images you provided now look much better.  
> 
> However, you need to re-add these images to each tab for the updates to take effect.

So when you are gonna add the features .and speed up the smooth scroll

**Comment by Droyk** [comment]
[**@eaufavor**](https://github.com/eaufavor) commented on [Jan 30, 2016, 3:20 AM GMT+5:30](https://github.com/eaufavor/Modern-New-Tab-Page-NoAd/issues/2#issuecomment-176984963 "2016-01-29T21:50:55Z - Replied by Github Comment Enhancer"):
> [@Droyk](https://github.com/Droyk) I made several changes to improve the quality of the logos.
> 
> 1.  logos now have more pixels so they look better
> 2.  logos are now larger
> 3.  the extension now will remove transparent edges of a logo to fit the tiles better.
> 
> So, to me, the images you provided now look much better.  
> 
> However, you need to re-add these images to each tab for the updates to take effect.

plz respond @eaufavor  i am waiting for you here plz

**Comment by Droyk** [comment]
And @eaufavor  Chrome url's not working on your new tab 

for e.g. add this url on the tab chrome://history/ 
it will not display the history page but it will only display the http page plzfix it by removing the http page from chrome urls

**Comment by eaufavor** [comment]
@Droyk  Sorry about the delay. I've been occupied these days. 
I just fixed the scrolling speed for smooth scroll. Tell me if it's still too slow, I might make it adjustable. The chrome urls issue has been fixed as well. Try it out. You might need to re-enter the broken chrome urls.

The logo zooming and ctrl+open features have been in my mind for a while. It will take some time though.  Stay tuned.

**Comment by Droyk** [comment]
[**@eaufavor**](https://github.com/eaufavor) commented on [Feb 4, 2016, 10:27 PM GMT+5:30](https://github.com/eaufavor/Modern-New-Tab-Page-NoAd/issues/2#issuecomment-179944889):

> [@Droyk](https://github.com/Droyk)  Sorry about the delay. I've been occupied these days.   
> 
> I just fixed the scrolling speed for smooth scroll. Tell me if it's still too slow, I might make it adjustable. The chrome urls issue has been fixed as well. Try it out. You might need to re-enter the broken chrome urls.
> 
> The logo zooming and ctrl+open features have been in my mind for a while. It will take some time though.  Stay tuned.
1. Thanxx @eaufavor for replying and updating it but still i am seeing quite a low speed for e.g. if i deselect and refresh the page scroll speed becomes quite fast that kind of speed i want but if i select smooth scroll it will become slow plz make it fast as normal mode thanxxx 
2. Some chrome url's are not working for e.g. chrome-extension://iffpnhdnfeeadmggdiojbnagempmklff/newtab.html

**3. Urgent problem plz fix this first no matter the condition plz see this video** https://streamable.com/4yfo 

**I have been trying to solve this for 15 hours 15 fucking hours plz** 
**Here is the file i exported plz see this and help me .........fix this bug plz i cant do anything at alll**
http://1drv.ms/1PY33PT

**Important note this bug is seem to be only happens when i load image in it you could say when yyou have 40 to 50 with image link this bug will happen .......if 80 to 90 tiles his bug will happen .....plz fix this bug thanxx**

**Comment by Droyk** [comment]
@eaufavor  i know you are really busy and i am really sorry about i am asking you but can you plz fix this bug only right now 

> plz see this video https://streamable.com/4yfo
> 
> I have been trying to solve this for 15 hours 15 fucking hours plz 
> Here is the file i exported plz see this and help me .........fix this bug plz i cant do anything at alll
> http://1drv.ms/1PY33PT
> 
> Important note this bug is seem to be only happens when i load image in it you could say when yyou have 40 to 50 with image link this bug will happen .......if 80 to 90 tiles his bug will happen .....plz fix this bug thanxx

**Comment by Droyk** [comment]
So @eaufavor  did you manage to fix the problem's i am having with

**Comment by Droyk** [comment]
So @eaufavor  how are you Its been a full month when you are going to fix the problems I told you ? 
it only giving me a purple screen that's all plz fix it

**Comment by eaufavor** [comment]
@Droyk Sorry for the delay. I've been travelling for the past month. When you have the problem, go to the chrome menu, then "more tools", then "developer tools". You will then find a panel pops out. Then go to the "Console" tab. Could you give me a screenshot or copy the messages shown in the Console tab? Thanks.

**Comment by Droyk** [comment]
Okay @eaufavor  Thanxx for respondig 
This is the error I am getting 

![screenshot_20160305010045](https://cloud.githubusercontent.com/assets/15848350/13539495/c7bdda14-e276-11e5-96ef-57b807ac21e5.png)

**Plz fix This error and Have a nice day ...**

**Comment by eaufavor** [comment]
@Droyk It looks like the problem is the (limited) internal storage is used up.

I uploaded a new version with unlimited storage. Please try it to see if it solves the problem. Thanks.

**Comment by Droyk** [comment]
[**@eaufavor**](https://github.com/eaufavor) commented on [Mar 11, 2016, 10:12 PM GMT+5:30](https://github.com/eaufavor/Modern-New-Tab-Page-NoAd/issues/2#issuecomment-195444664 "2016-03-11T16:42:12Z - Replied by Github Comment Enhancer"):
> [@Droyk](https://github.com/Droyk) It looks like the problem is the (limited) internal storage is used up.
> 
> I uploaded a new version with unlimited storage. Please try it to see if it solves the problem. Thanks.

It didn't work at all I am getting the error 
![screenshot_20160311233352](https://cloud.githubusercontent.com/assets/15848350/13710939/fbd81236-e7e1-11e5-9cb9-2994d7c70fe8.png)

**Comment by Droyk** [comment]
[**@eaufavor**](https://github.com/eaufavor) commented on [Mar 11, 2016, 10:12 PM GMT+5:30](https://github.com/eaufavor/Modern-New-Tab-Page-NoAd/issues/2#issuecomment-195444664):

> [@Droyk](https://github.com/Droyk) It looks like the problem is the (limited) internal storage is used up.
> 
> I uploaded a new version with unlimited storage. Please try it to see if it solves the problem. Thanks.

It didn't work at all I am getting the same error with different number as you can see in this pic 
![screenshot_20160311233352](https://cloud.githubusercontent.com/assets/15848350/13711001/4df741f4-e7e2-11e5-91ca-e75dd9850d54.png)

**Comment by Droyk** [comment]
[**@eaufavor**](https://github.com/eaufavor) commented on [Mar 11, 2016, 10:12 PM GMT+5:30](https://github.com/eaufavor/Modern-New-Tab-Page-NoAd/issues/2#issuecomment-195444664 "2016-03-11T16:42:12Z - Replied by Github Comment Enhancer"):
> [@Droyk](https://github.com/Droyk) It looks like the problem is the (limited) internal storage is used up.
> 
> I uploaded a new version with unlimited storage. Please try it to see if it solves the problem. Thanks.

So what happened @eaufavor when you are going to fix it I got that you are buys doing something but You can atleast sent me reply ..that you will fix it after a month or day or as per your schedule ...

**I can wait @eaufavor  but plz when I message you plz send me a reply for confirmation thanxx**

**Comment by eaufavor** [comment]
@Droyk 

It looks like it's harder to solve this problem. I'll try finding some time to fix it. Thanks a lot.

**Comment by Droyk** [comment]
[**@eaufavor**](https://github.com/eaufavor) commented on [Mar 17, 2016, 12:49 AM GMT+5:30](https://github.com/eaufavor/Modern-New-Tab-Page-NoAd/issues/2#issuecomment-197498478 "2016-03-16T19:19:46Z - Replied by Github Comment Enhancer"):
> [@Droyk](https://github.com/Droyk) 
> 
> It looks like it's harder to solve this problem. I'll try finding some time to fix it. Thanks a lot.

Okay @eaufavor when you have some free time Plz fix this i Will be waiting

**Comment by Droyk** [comment]
[**@eaufavor**](https://github.com/eaufavor) commented on [Mar 17, 2016, 12:49 AM GMT+5:30](https://github.com/eaufavor/Modern-New-Tab-Page-NoAd/issues/2#issuecomment-197498478):

> [@Droyk](https://github.com/Droyk) 
> 
> It looks like it's harder to solve this problem. I'll try finding some time to fix it. Thanks a lot.

So Its been 23 days @eaufavor **Do You Still Want More Time**

**Comment by Droyk** [comment]
@eaufavor **No one is busy enough that can't even reply a message**
If you want fix this then plz tell me 
**If you don't want to then don't waste my time It's already been 2 months**
I was waiting patiently until Now But Now I can't Nor I really want too
_**if you to fix this problem then plz do it
if you don't want to fix this then plz say it**_

**Comment by iBreakEverything** [comment]
@Droyk yo, it's your boy with the updates (5 years later)
check this out https://github.com/iBreakEverything/MNTP-Reloaded

**Comment by Droyk** [comment]
Thanks but I don't use this kind of new tab anymore. I figured this is too time-consuming. yes, it looks good. you want it as eye candy go for it. but for productivity reasons, this doesn't help! too-much scrolling, change the tiles and all which is going to be every time if you want a good looking new tab. too much time consumption. I use homely now. a [chrome extension](https://chrome.google.com/webstore/detail/homely/fplghnonomhbnlhdnmjpipoomkjdpeim) which has increased my productivity 1000% over the last 3 years or so. I suggest you take a look at it. coz it is great! it has its faults. the developer is kinda lazy but so far I had fun using it! if you're free see if you can fix some bugs there!

by the way, Umm are you the same user as @eaufavor I mean is @iBreakEverything your second id/alias or you're just a different user!

**Comment by Droyk** [comment]
@iBreakEverything Also don't forget to add your version to the chrome store. the users who like customization will love it! coz it is great eye candy & great fun if one has time for it!

**Comment by Droyk** [comment]
@iBreakEverything I like your Avatar, man! Don't remove it!

**Comment by iBreakEverything** [comment]
@Droyk 
 - that extension looks nice, ill look into it
 - im a different user of this extension, i updated it cause i needed it
 - adding the extension to chrome store is not worth it ($5 to publish it and manifest v3 is right around the corner), plus i don't know if i can, as this repo does not have a license
 - yes, greatest avatar on the web right after this one -> [link](https://image.pngaaa.com/659/1374659-middle.png)
